# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
auth0JavaJwt = "4.4.0"
commonmark = "0.27.0"
gradleNodePluginVersion = "7.0.2"
gradleVersionsPlugin = "0.53.0"
jimfs = "1.3.1"
kotlin = "2.2.21"
kotlinxCoroutines = "1.10.2"
kotlinxDatetime = "0.6.2"
kotlinxHtml = "0.11.0"
kotlinxSerializationJSON = "1.8.1"
ktor = "3.3.3"
logback = "1.5.21"
mcpKotlin = "0.7.4"
microprofileConfig = "3.1"
slf4j = "2.0.17"
smallryeConfig = "3.15.0"
sqlite="3.45.1.0"

[libraries]
auth0JavaJwt = { module = "com.auth0:java-jwt", version.ref = "auth0JavaJwt" }
commonmark = { module = "org.commonmark:commonmark", version.ref = "commonmark" }
commonmarkYamlFrontMatter = { module = "org.commonmark:commonmark-ext-yaml-front-matter", version.ref = "commonmark" }
jimfs = { module = "com.google.jimfs:jimfs", version.ref = "jimfs" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinxHtml = { module = "org.jetbrains.kotlinx:kotlinx-html-jvm", version.ref = "kotlinxHtml"}
ktorServerAuth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktorServerAuthJwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor" }
ktorServerCore = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktorServerNetty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktorServerContentNegotiation = { module = "io.ktor:ktor-server-content-negotiation-jvm", version.ref = "ktor" }
ktorSerializationKotlinxJson = { module = "io.ktor:ktor-serialization-kotlinx-json-jvm", version.ref = "ktor" }
ktorServerSse = { module = "io.ktor:ktor-server-sse-jvm", version.ref = "ktor" }
ktorServerStatusPages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }
ktorClientCore = { module = "io.ktor:ktor-client-core-jvm", version.ref = "ktor" }
ktorClientCio = { module = "io.ktor:ktor-client-cio-jvm", version.ref = "ktor" }
ktorClientContentNegotiation = { module = "io.ktor:ktor-client-content-negotiation-jvm", version.ref = "ktor" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback"}
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j"}
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j"}
mcpKotlinServer = { module = "io.modelcontextprotocol:kotlin-sdk-server", version.ref = "mcpKotlin" }
microprofileConfigApi = { module = "org.eclipse.microprofile.config:microprofile-config-api", version.ref = "microprofileConfig" }
smallryeConfig = { module = "io.smallrye.config:smallrye-config", version.ref = "smallryeConfig" }
sqliteJdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }

# Libraries can be bundled together for easier import
[bundles]
commonmark = ["commonmark", "commonmarkYamlFrontMatter"]
kotlinxEcosystem = ["kotlinxDatetime", "kotlinxSerialization", "kotlinxCoroutines"]
slf4jImpl = ["slf4j", "logback"]
slf4j = ["slf4j"]
slf4jTests = ["slf4j", "slf4j-simple"]

[plugins]
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
gradleVersionsPlugin = { id = "com.github.ben-manes.versions", version.ref = "gradleVersionsPlugin" }
gradleNodePlugin = { id = "com.github.node-gradle.node", version.ref = "gradleNodePluginVersion"}
